[project]
name = "parsing-documents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.29.5",
    "ollama>=0.4.7",
    "pillow>=11.1.0",
    "streamlit>=1.43.2",
]
